name: CI - Build, Test & Allure Report

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Tests build and execution with Maven
        run: mvn -B clean verify
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          mvn io.qameta.allure:allure-maven:report
          rm -rf allure-report
          cp -r target/site/allure-maven-plugin/* allure-report

      - name: Publish Allure Report on GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'